#if !defined(AFX_CTTEXT_H__A77CE526_0D6D_40D8_B02B_E66D3EB49304__INCLUDED_)
#define AFX_CTTEXT_H__A77CE526_0D6D_40D8_B02B_E66D3EB49304__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CctText wrapper class

class CctText : public CWnd
{
protected:
	DECLARE_DYNCREATE(CctText)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7aaeca0, 0x1a03, 0x11cf, { 0x9d, 0xfe, 0x9c, 0x7d, 0x37, 0xb2, 0xc9, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	CString GetFontName();
	void SetFontName(LPCTSTR);
	BOOL GetFontBold();
	void SetFontBold(BOOL);
	BOOL GetFontItalic();
	void SetFontItalic(BOOL);
	BOOL GetFontStrikethru();
	void SetFontStrikethru(BOOL);
	BOOL GetFontUnderline();
	void SetFontUnderline(BOOL);
	float GetFontSize();
	void SetFontSize(float);
	long GetBorderType();
	void SetBorderType(long);
	long GetTextPosition();
	void SetTextPosition(long);
	long GetPicPosition();
	void SetPicPosition(long);
	short GetTextAngle();
	void SetTextAngle(short);
	CPicture GetPicture();
	void SetPicture(LPDISPATCH);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long);
	BOOL GetSingleLine();
	void SetSingleLine(BOOL);
	unsigned long GetThreeDColor();
	void SetThreeDColor(unsigned long);
	BOOL GetThreeDText();
	void SetThreeDText(BOOL);
	unsigned long GetBorderColor();
	void SetBorderColor(unsigned long);
	long GetAlignment();
	void SetAlignment(long);
	short GetTextXOffset();
	void SetTextXOffset(short);
	short GetTextYOffset();
	void SetTextYOffset(short);
	BOOL GetWordWrap();
	void SetWordWrap(BOOL);
	BOOL GetThinBorder();
	void SetThinBorder(BOOL);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CTTEXT_H__A77CE526_0D6D_40D8_B02B_E66D3EB49304__INCLUDED_)
