/*******************************************************************************
' CUSCorePDACaster.h
'
' Copyright (c) 2004 by Miracom,Inc.
' All rights reserved.
'
' Generated by XGen 4.0
'
' Created at Wed Apr 16 11:36:50 KST 2008
'
' Author : Miracom
' Description : Generated by XGen4.3.0.3
'******************************************************************************/

#ifndef _XGEN_CUSCOREPDA_SENDER_H
#define _XGEN_CUSCOREPDA_SENDER_H

#include "CUSCorePDAType.h"


extern IOIStatus send_CUS_Update_PDA_Silsa_Input(CUS_Update_PDA_Silsa_input_In_Tag *CUS_Update_PDA_Silsa_input_In, PDA_Cmn_Out_Tag *PDA_Cmn_Out, LPTSTR channel, int ttl, int mode);
extern IOIStatus send_CUS_Update_PDA_Direct_Packing_Label(CUS_Update_PDA_Direct_Packing_Label_In_Tag *CUS_Update_PDA_Direct_Packing_Label_In, PDA_Cmn_Out_Tag *PDA_Cmn_Out, LPTSTR channel, int ttl, int mode);
extern IOIStatus send_CUS_Update_PDA_Optics_Mat_Output(CUS_Update_PDA_Optics_Mat_Output_in_Tag *CUS_Update_PDA_Optics_Mat_Output_in, PDA_Cmn_Out_Tag *PDA_Cmn_Out, LPTSTR channel, int ttl, int mode);
extern IOIStatus send_CUS_Update_PDA_Tran_Out_Stock(CUS_Update_PDA_Tran_Out_Stock_in_Tag *CUS_Update_PDA_Tran_Out_Stock_in, PDA_Cmn_Out_Tag *PDA_Cmn_Out, LPTSTR channel, int ttl, int mode);
extern IOIStatus send_CUS_View_PDA_Ship_LDP_Label(CUS_View_PDA_Ship_LDP_Label_In_Tag *CUS_View_PDA_Ship_LDP_Label_In, CUS_View_PDA_Ship_LDP_Label_Out_Tag *CUS_View_PDA_Ship_LDP_Label_Out, LPTSTR channel, int ttl, int mode);
extern IOIStatus send_CUS_View_PDA_GCM_Table_List(CUS_View_PDA_GCM_Table_In_Tag *CUS_View_PDA_GCM_Table_In, CUS_View_PDA_GCM_Table_Out_Tag *CUS_View_PDA_GCM_Table_Out, LPTSTR channel, int ttl, int mode);

#endif /* _XGEN_CUSCOREPDA_SENDER_H */

