/*******************************************************************************
' CUSDGWType.h
'
' Copyright (c) 2004 by Miracom,Inc.
' All rights reserved.
'
' Generated by XGen 4.0
'
' Created at Thu Apr 24 11:25:03 KST 2008
'
' Author : Miracom
' Description : Generated by XGen4.3.0.1
'******************************************************************************/

#ifndef _XGEN_CUSCOREDGW_TYPE_H
#define _XGEN_CUSCOREDGW_TYPE_H

#include "h101stub.h"


typedef struct CUSDGW_Cmn_Out_Tag
{
    char h_status_value;
    char h_msg_code[10];
    char h_msg[200];
    char h_field_msg[200];
    char h_db_err_msg[200];
} ;
extern void serialize_CUSDGW_Cmn_Out_Tag(HTransformer former, CUSDGW_Cmn_Out_Tag *source_type);
extern void transform_CUSDGW_Cmn_Out_Tag(HTransformer former, CUSDGW_Cmn_Out_Tag *target_type);

typedef struct CUSDGW_Send_In_Tag_data_list
{
    char item_type;
    char item_name[20];
    char item_value[100];
} ;
extern void serialize_CUSDGW_Send_In_Tag_data_list(HTransformer former, CUSDGW_Send_In_Tag_data_list *source_type);
extern void transform_CUSDGW_Send_In_Tag_data_list(HTransformer former, CUSDGW_Send_In_Tag_data_list *target_type);

typedef struct CUSDGW_Send_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    int h_hist_seq;
    char back_time[14];
    char lot_id[25];
    char res_id[20];
    int count;
    int _size_data_list;
    CUSDGW_Send_In_Tag_data_list data_list[1000];
    char resv_field1[30];
    char resv_field2[30];
    char resv_field3[30];
    char resv_field4[30];
    char resv_field5[30];
} ;
extern void serialize_CUSDGW_Send_In_Tag(HTransformer former, CUSDGW_Send_In_Tag *source_type);
extern void transform_CUSDGW_Send_In_Tag(HTransformer former, CUSDGW_Send_In_Tag *target_type);

typedef struct CUSDGW_SendAuto_In_Tag_data_tbl_item
{
    char name[30];
    char value[30];
} ;
extern void serialize_CUSDGW_SendAuto_In_Tag_data_tbl_item(HTransformer former, CUSDGW_SendAuto_In_Tag_data_tbl_item *source_type);
extern void transform_CUSDGW_SendAuto_In_Tag_data_tbl_item(HTransformer former, CUSDGW_SendAuto_In_Tag_data_tbl_item *target_type);

typedef struct CUSDGW_SendAuto_In_Tag_data_tbl
{
    int item_count;
    int _size_item;
    CUSDGW_SendAuto_In_Tag_data_tbl_item item[100];
} ;
extern void serialize_CUSDGW_SendAuto_In_Tag_data_tbl(HTransformer former, CUSDGW_SendAuto_In_Tag_data_tbl *source_type);
extern void transform_CUSDGW_SendAuto_In_Tag_data_tbl(HTransformer former, CUSDGW_SendAuto_In_Tag_data_tbl *target_type);

typedef struct CUSDGW_SendAuto_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    int h_hist_seq;
    char back_time[14];
    char lot_id[25];
    char res_id[20];
    int count;
    int _size_data_tbl;
    CUSDGW_SendAuto_In_Tag_data_tbl data_tbl[1000];
    char resv_field1[30];
    char resv_field2[30];
    char resv_field3[30];
    char resv_field4[30];
    char resv_field5[30];
} ;
extern void serialize_CUSDGW_SendAuto_In_Tag(HTransformer former, CUSDGW_SendAuto_In_Tag *source_type);
extern void transform_CUSDGW_SendAuto_In_Tag(HTransformer former, CUSDGW_SendAuto_In_Tag *target_type);

typedef struct CUSDGW_ViewSanpoData_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    char lot_id[25];
    long seq;
    char res_id[10];
    char item_value1[30];
    char from_time[14];
    char to_time[14];
    char next_lot_id[25];
    long next_seq;
    long next_data_seq;
} ;
extern void serialize_CUSDGW_ViewSanpoData_In_Tag(HTransformer former, CUSDGW_ViewSanpoData_In_Tag *source_type);
extern void transform_CUSDGW_ViewSanpoData_In_Tag(HTransformer former, CUSDGW_ViewSanpoData_In_Tag *target_type);

typedef struct CUSDGW_ViewSanpoData_Out_Tag_sanpo_data_tbl
{
    char factory[10];
    char lot_id[25];
    long seq;
    long data_seq;
    char tran_time[14];
    char res_id[10];
    char item_type;
    long count;
    char item_value1[30];
    char item_value2[30];
    char item_value3[30];
    char item_value4[30];
    char item_value5[30];
    char item_value6[30];
    char item_value7[30];
    char item_value8[30];
    char item_value9[30];
    char item_value10[30];
    char item_value11[30];
    char item_value12[30];
    char item_value13[30];
    char item_value14[30];
    char item_value15[30];
    char item_value16[30];
    char item_value17[30];
    char item_value18[30];
    char item_value19[30];
    char item_value20[30];
    char item_value21[30];
    char item_value22[30];
    char item_value23[30];
    char item_value24[30];
    char item_value25[30];
    char item_value26[30];
    char item_value27[30];
    char item_value28[30];
    char item_value29[30];
    char item_value30[30];
} ;
extern void serialize_CUSDGW_ViewSanpoData_Out_Tag_sanpo_data_tbl(HTransformer former, CUSDGW_ViewSanpoData_Out_Tag_sanpo_data_tbl *source_type);
extern void transform_CUSDGW_ViewSanpoData_Out_Tag_sanpo_data_tbl(HTransformer former, CUSDGW_ViewSanpoData_Out_Tag_sanpo_data_tbl *target_type);

typedef struct CUSDGW_ViewSanpoData_Out_Tag
{
    char h_status_value;
    char h_msg_code[10];
    char h_msg[200];
    char h_field_msg[200];
    char h_db_err_msg[200];
    long count;
    char next_lot_id[25];
    long next_seq;
    long next_data_seq;
    int _size_sanpo_data_tbl;
    CUSDGW_ViewSanpoData_Out_Tag_sanpo_data_tbl sanpo_data_tbl[1000];
} ;
extern void serialize_CUSDGW_ViewSanpoData_Out_Tag(HTransformer former, CUSDGW_ViewSanpoData_Out_Tag *source_type);
extern void transform_CUSDGW_ViewSanpoData_Out_Tag(HTransformer former, CUSDGW_ViewSanpoData_Out_Tag *target_type);

typedef struct CUSInsp_Lbl_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    int h_hist_seq;
    char back_time[14];
    char lot_id[25];
    char res_id[20];
    double qty;
    char resv_field1[30];
    char resv_field2[30];
    char resv_field3[30];
    char resv_field4[30];
    char resv_field5[30];
} ;
extern void serialize_CUSInsp_Lbl_In_Tag(HTransformer former, CUSInsp_Lbl_In_Tag *source_type);
extern void transform_CUSInsp_Lbl_In_Tag(HTransformer former, CUSInsp_Lbl_In_Tag *target_type);


#endif /* _XGEN_CUSCOREDGW_TYPE_H */

