/*******************************************************************************
' CUSCorePDAType.h
'
' Copyright (c) 2004 by Miracom,Inc.
' All rights reserved.
'
' Generated by XGen 4.0
'
' Created at Wed Apr 16 11:36:50 KST 2008
'
' Author : Miracom
' Description : Generated by XGen4.3.0.3
'******************************************************************************/

#ifndef _XGEN_CUSCOREPDA_TYPE_H
#define _XGEN_CUSCOREPDA_TYPE_H

#include "h101stub.h"


typedef struct PDA_Cmn_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
} ;

typedef struct PDA_Cmn_Out_Tag
{
    char h_status_value;
    char h_msg_code[10];
    char h_msg[200];
    char h_field_msg[200];
    char h_db_err_msg[200];
} ;

typedef struct CUS_Update_PDA_Silsa_input_In_Tag_pda_list
{
    char outbox_no[20];
    char mat_id[20];
    double qty_1;
} ;

typedef struct CUS_Update_PDA_Silsa_input_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    char factory[10];
    char work_date[14];
    char mat_id[20];
    char mat_desc[50];
    char lot_id[20];
    double ins_qty;
    double inv_qty;
    char create_user_id[20];
    char create_time[14];
    char update_user_id[20];
    char update_time[14];
    char shp_cmf_1[30];
    char shp_cmf_2[30];
    char shp_cmf_3[30];
    char shp_cmf_4[30];
    char shp_cmf_5[30];
    char shp_cmf_6[30];
    char shp_cmf_7[30];
    char shp_cmf_8[30];
    char shp_cmf_9[30];
    char shp_cmf_10[30];
    int _size_pda_list;
    CUS_Update_PDA_Silsa_input_In_Tag_pda_list pda_list[100];
} ;

typedef struct CUS_Update_PDA_Direct_Packing_Label_In_Tag_pda_list
{
    char barcode[30];
} ;

typedef struct CUS_Update_PDA_Direct_Packing_Label_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    char factory[10];
    char work_date[8];
    char prod_date[14];
    char inbox_no[30];
    double inbox_seq;
    char barcode[30];
    char label_id[25];
    char prod_name[50];
    char mat_id[30];
    char mat_desc[50];
    char mat_type[20];
    char pol_type[30];
    char lot_id[25];
    char cust_mat_id[30];
    char cust_mat_desc[50];
    char mat_size[20];
    double pack_qty;
    char order_no[25];
    char print_time[14];
    double tot_qty;
    char side_flag;
    double print_cnt;
    char residue_fg;
    double residue_qty;
    char add_fg;
    char from_to_inbox_no[30];
    char delete_fg;
    char create_user_id[20];
    char create_time[14];
    char update_user_id[20];
    char update_time[14];
    char lbl_cmf_1[30];
    char lbl_cmf_2[30];
    char lbl_cmf_3[30];
    char lbl_cmf_4[30];
    char lbl_cmf_5[30];
    char lbl_cmf_6[30];
    char lbl_cmf_7[30];
    char lbl_cmf_8[30];
    char lbl_cmf_9[30];
    char lbl_cmf_10[30];
    int _size_pda_list;
    CUS_Update_PDA_Direct_Packing_Label_In_Tag_pda_list pda_list[100];
} ;

typedef struct CUS_Update_PDA_Optics_Mat_Output_in_Tag_pda_list
{
    char barcode[30];
} ;

typedef struct CUS_Update_PDA_Optics_Mat_Output_in_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    char factory[10];
    char work_date[8];
    char prod_date[14];
    char outbox_no[30];
    double outbox_seq;
    char barcode[30];
    char label_id[25];
    char prod_name[50];
    char mat_id[30];
    char mat_desc[50];
    char mat_type[20];
    char pol_type[30];
    char lot_id[25];
    char inbox_no[30];
    char customer_id[25];
    char customer_desc[25];
    char cust_mat_id[20];
    char cust_mat_desc[50];
    char mat_size[20];
    double pack_qty;
    char avail_time[14];
    char order_no[25];
    char print_time[14];
    double tot_qty;
    double print_cnt;
    char residue_fg;
    double residue_qty;
    char add_fg;
    char ship_fg;
    char ship_time[14];
    char from_to_outbox_no[30];
    char delete_fg;
    char create_user_id[20];
    char create_time[14];
    char update_user_id[20];
    char update_time[14];
    char lot_id_1[25];
    char lot_id_2[25];
    char lot_id_3[25];
    char pol_type_1[30];
    char pol_type_2[30];
    char pol_type_3[30];
    char pol_type_4[30];
    char lbl_cmf_1[30];
    char lbl_cmf_2[30];
    char lbl_cmf_3[30];
    char lbl_cmf_4[30];
    char lbl_cmf_5[30];
    char lbl_cmf_6[30];
    char lbl_cmf_7[30];
    char lbl_cmf_8[30];
    char lbl_cmf_9[30];
    char lbl_cmf_10[30];
    int _size_pda_list;
    CUS_Update_PDA_Optics_Mat_Output_in_Tag_pda_list pda_list[100];
} ;

typedef struct CUS_Update_PDA_Tran_Out_Stock_in_Tag_lot_list
{
    char lot_id[25];
    char Carraier_id[25];
} ;

typedef struct CUS_Update_PDA_Tran_Out_Stock_in_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    int count;
    char oper[10];
    char lot_cmf_1[30];
    char lot_cmf_2[30];
    char lot_cmf_3[30];
    char lot_cmf_4[30];
    char lot_cmf_5[30];
    char lot_cmf_6[30];
    char lot_cmf_7[30];
    char lot_cmf_8[30];
    char lot_cmf_9[30];
    char lot_cmf_10[30];
    int _size_lot_list;
    CUS_Update_PDA_Tran_Out_Stock_in_Tag_lot_list lot_list[100];
} ;

typedef struct CUS_View_PDA_Ship_LDP_Label_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    char factory[10];
    char barcode[30];
} ;

typedef struct CUS_View_PDA_Ship_LDP_Label_Out_Tag
{
    char h_status_value;
    char h_msg_code[10];
    char h_msg[200];
    char h_field_msg[200];
    char h_db_err_msg[200];
    int count;
    char factory[10];
    char customer_id[30];
    char barcode[30];
    char dw_code[30];
    int barcode_seq;
    char cust_model_id[30];
    char lot_id[25];
    int pack_qty;
    char cust_mat_code[30];
    char sap_mat_code[30];
    char vendor_mat_id[50];
    int lot_qty;
    char prod_time[14];
    char print_user_id[20];
    char print_time[14];
    char lbl_cmf_1[30];
    char lbl_cmf_2[30];
    char lbl_cmf_3[30];
    char lbl_cmf_4[30];
    char lbl_cmf_5[30];
    char lbl_cmf_6[30];
    char lbl_cmf_7[30];
    char lbl_cmf_8[30];
    char lbl_cmf_9[30];
    char lbl_cmf_10[30];
} ;

typedef struct CUS_View_PDA_GCM_Table_In_Tag
{
    char h_passport[100];
    char h_language;
    char h_factory[10];
    char h_user_id[20];
    char h_password[20];
    char h_proc_step;
    char factory[10];
    char table_name[20];
    char key_1[30];
    char key_2[30];
    char next_key_1[30];
    char next_key_2[30];
    char next_data_1[50];
} ;

typedef struct CUS_View_PDA_GCM_Table_Out_Tag_data_list
{
    char key_1[30];
    char key_2[30];
    char data_1[50];
    char data_2[50];
    char data_3[50];
    char data_4[50];
    char data_5[50];
    char data_6[50];
    char data_7[50];
    char data_8[50];
    char data_9[50];
    char data_10[50];
} ;

typedef struct CUS_View_PDA_GCM_Table_Out_Tag
{
    char h_status_value;
    char h_msg_code[10];
    char h_msg[200];
    char h_field_msg[200];
    char h_db_err_msg[200];
    int count;
    char next_key_1[30];
    char next_key_2[30];
    char next_data_1[50];
    int _size_data_list;
    CUS_View_PDA_GCM_Table_Out_Tag_data_list data_list[100];
} ;


extern void serialize_PDA_Cmn_In_Tag(HTransformer former, PDA_Cmn_In_Tag *source);
extern void serialize_PDA_Cmn_Out_Tag(HTransformer former, PDA_Cmn_Out_Tag *source);
extern void serialize_CUS_Update_PDA_Silsa_input_In_Tag_pda_list(HTransformer former, CUS_Update_PDA_Silsa_input_In_Tag_pda_list *source);
extern void serialize_CUS_Update_PDA_Silsa_input_In_Tag(HTransformer former, CUS_Update_PDA_Silsa_input_In_Tag *source);
extern void serialize_CUS_Update_PDA_Direct_Packing_Label_In_Tag_pda_list(HTransformer former, CUS_Update_PDA_Direct_Packing_Label_In_Tag_pda_list *source);
extern void serialize_CUS_Update_PDA_Direct_Packing_Label_In_Tag(HTransformer former, CUS_Update_PDA_Direct_Packing_Label_In_Tag *source);
extern void serialize_CUS_Update_PDA_Optics_Mat_Output_in_Tag_pda_list(HTransformer former, CUS_Update_PDA_Optics_Mat_Output_in_Tag_pda_list *source);
extern void serialize_CUS_Update_PDA_Optics_Mat_Output_in_Tag(HTransformer former, CUS_Update_PDA_Optics_Mat_Output_in_Tag *source);
extern void serialize_CUS_Update_PDA_Tran_Out_Stock_in_Tag_lot_list(HTransformer former, CUS_Update_PDA_Tran_Out_Stock_in_Tag_lot_list *source);
extern void serialize_CUS_Update_PDA_Tran_Out_Stock_in_Tag(HTransformer former, CUS_Update_PDA_Tran_Out_Stock_in_Tag *source);
extern void serialize_CUS_View_PDA_Ship_LDP_Label_In_Tag(HTransformer former, CUS_View_PDA_Ship_LDP_Label_In_Tag *source);
extern void serialize_CUS_View_PDA_Ship_LDP_Label_Out_Tag(HTransformer former, CUS_View_PDA_Ship_LDP_Label_Out_Tag *source);
extern void serialize_CUS_View_PDA_GCM_Table_In_Tag(HTransformer former, CUS_View_PDA_GCM_Table_In_Tag *source);
extern void serialize_CUS_View_PDA_GCM_Table_Out_Tag_data_list(HTransformer former, CUS_View_PDA_GCM_Table_Out_Tag_data_list *source);
extern void serialize_CUS_View_PDA_GCM_Table_Out_Tag(HTransformer former, CUS_View_PDA_GCM_Table_Out_Tag *source);

extern void transform_PDA_Cmn_In_Tag(HTransformer former, PDA_Cmn_In_Tag *target);
extern void transform_PDA_Cmn_Out_Tag(HTransformer former, PDA_Cmn_Out_Tag *target);
extern void transform_CUS_Update_PDA_Silsa_input_In_Tag_pda_list(HTransformer former, CUS_Update_PDA_Silsa_input_In_Tag_pda_list *target);
extern void transform_CUS_Update_PDA_Silsa_input_In_Tag(HTransformer former, CUS_Update_PDA_Silsa_input_In_Tag *target);
extern void transform_CUS_Update_PDA_Direct_Packing_Label_In_Tag_pda_list(HTransformer former, CUS_Update_PDA_Direct_Packing_Label_In_Tag_pda_list *target);
extern void transform_CUS_Update_PDA_Direct_Packing_Label_In_Tag(HTransformer former, CUS_Update_PDA_Direct_Packing_Label_In_Tag *target);
extern void transform_CUS_Update_PDA_Optics_Mat_Output_in_Tag_pda_list(HTransformer former, CUS_Update_PDA_Optics_Mat_Output_in_Tag_pda_list *target);
extern void transform_CUS_Update_PDA_Optics_Mat_Output_in_Tag(HTransformer former, CUS_Update_PDA_Optics_Mat_Output_in_Tag *target);
extern void transform_CUS_Update_PDA_Tran_Out_Stock_in_Tag_lot_list(HTransformer former, CUS_Update_PDA_Tran_Out_Stock_in_Tag_lot_list *target);
extern void transform_CUS_Update_PDA_Tran_Out_Stock_in_Tag(HTransformer former, CUS_Update_PDA_Tran_Out_Stock_in_Tag *target);
extern void transform_CUS_View_PDA_Ship_LDP_Label_In_Tag(HTransformer former, CUS_View_PDA_Ship_LDP_Label_In_Tag *target);
extern void transform_CUS_View_PDA_Ship_LDP_Label_Out_Tag(HTransformer former, CUS_View_PDA_Ship_LDP_Label_Out_Tag *target);
extern void transform_CUS_View_PDA_GCM_Table_In_Tag(HTransformer former, CUS_View_PDA_GCM_Table_In_Tag *target);
extern void transform_CUS_View_PDA_GCM_Table_Out_Tag_data_list(HTransformer former, CUS_View_PDA_GCM_Table_Out_Tag_data_list *target);
extern void transform_CUS_View_PDA_GCM_Table_Out_Tag(HTransformer former, CUS_View_PDA_GCM_Table_Out_Tag *target);

#endif /* _XGEN_CUSCOREPDA_TYPE_H */

