/*******************************************************************************
' CUSDGWTuner.h
'
' Copyright (c) 2004 by Miracom,Inc.
' All rights reserved.
'
' Generated by XGen 4.0
'
' Created at 
'
' Author : Miracom
' Description : Generated by XGen4.3.0.1
'******************************************************************************/

#ifndef _XGEN_CUSCOREDGW_RECEIVER_H
#define _XGEN_CUSCOREDGW_RECEIVER_H

#include "CUSDGWType.h"

extern void registCUSCoreDGW();

extern IOIStatus recv_CUSDGW_Send(IOISession session, IOIMessage msg);
extern IOIStatus recv_CUSInsp_Lbl(IOISession session, IOIMessage msg);
extern IOIStatus recv_CUSInsp_Lbl_AIS(IOISession session, IOIMessage msg);
extern IOIStatus recv_CUSDGW_SendAuto(IOISession session, IOIMessage msg);
extern IOIStatus recv_CUSDGW_ViewSanpoData(IOISession session, IOIMessage msg);
extern IOIStatus CUSDGW_Send(CUSDGW_Send_In_Tag *CUSDGW_Send_In);
extern IOIStatus CUSInsp_Lbl(CUSInsp_Lbl_In_Tag *CUSInsp_Lbl_In);
extern IOIStatus CUSInsp_Lbl_AIS(CUSInsp_Lbl_In_Tag *CUSInsp_Lbl_In, CUSDGW_Cmn_Out_Tag *CUSDGW_Cmn_Out);
extern IOIStatus CUSDGW_SendAuto(CUSDGW_SendAuto_In_Tag *CUSDGW_SendAuto_In, CUSDGW_Cmn_Out_Tag *CUSDGW_Cmn_Out);
extern IOIStatus CUSDGW_ViewSanpoData(CUSDGW_ViewSanpoData_In_Tag *CUSDGW_ViewSanpoData_In, CUSDGW_ViewSanpoData_Out_Tag *CUSDGW_ViewSanpoData_Out);


#endif /* _XGEN_CUSCOREDGW_RECEIVER_H */

