/*******************************************************************************
' CUSDGWTuner.c
'
' Copyright (c) 2004 by Miracom,Inc.
' All rights reserved.
'
' Generated by XGen 4.0
'
' Created at 
'
' Author : Miracom
' Description : Generated by XGen4.3.0.1
'******************************************************************************/

#ifdef _AFXDLL
#include "stdafx.h"
#endif
#include "CUSDGWTuner.h"

/* Initialize module context **************************************************/
XGEN_MODULE_BEGIN_CONTEXT(CUSCoreDGW)
    XGEN_OPERATION_REGIST_CONTEXT(CUSDGW_Send)
    XGEN_OPERATION_REGIST_CONTEXT(CUSInsp_Lbl)
    XGEN_OPERATION_REGIST_CONTEXT(CUSDGW_SendAuto)
    XGEN_OPERATION_REGIST_CONTEXT(CUSDGW_ViewSanpoData)
XGEN_MODULE_END_CONTEXT(CUSCoreDGW)
XGEN_MODULE_REGIST_CONTEXT(CUSCoreDGW, 4)


IOIStatus recv_CUSDGW_Send(IOISession session, IOIMessage msg)
{
    IOIStatus status = IOI_SUCCESS;
    CUSDGW_Send_In_Tag source_type;

    IxArray ioi_data_array = IOIMessageGetDataArray(msg);
    HTransformer former = CreateByteTransformer(&ioi_data_array);
    if(Null_Ptr != former)
    {
        transform_CUSDGW_Send_In_Tag(former, &source_type);
        DestroyTransformer(former);

        CUSDGW_Send(&source_type);
    }

    return status;
}

IOIStatus recv_CUSInsp_Lbl(IOISession session, IOIMessage msg)
{
    IOIStatus status = IOI_SUCCESS;
    CUSInsp_Lbl_In_Tag source_type;

    IxArray ioi_data_array = IOIMessageGetDataArray(msg);
    HTransformer former = CreateByteTransformer(&ioi_data_array);
    if(Null_Ptr != former)
    {
        transform_CUSInsp_Lbl_In_Tag(former, &source_type);
        DestroyTransformer(former);

        CUSInsp_Lbl(&source_type);
    }

    return status;
}

IOIStatus recv_CUSInsp_Lbl_AIS(IOISession session, IOIMessage msg)
{
    IOIStatus status = IOI_SUCCESS;
    CUSInsp_Lbl_In_Tag source_type;
    CUSDGW_Cmn_Out_Tag target_type;

    IxArray ioi_data_array = IOIMessageGetDataArray(msg);
    HTransformer former = CreateByteTransformer(&ioi_data_array);
    if(Null_Ptr != former)
    {
        transform_CUSInsp_Lbl_In_Tag(former, &source_type);
        DestroyTransformer(former);

        CUSInsp_Lbl_AIS(&source_type, &target_type);
        if(DT_REQUEST == (IOIMessageGetDelivery(msg) & 0x000f))
        {
            IOIMessage rep = IOIMessageCreateReply(msg);
            if(Null_Ptr != rep)
            {
                IxArray a_data;
                HStreamBuffer buffer = CreateStreamByteBuffer(Null_Ptr, IX_BYTE, 5, 10, 500);
                HOutputStream stream = CreateOutputStream(buffer);
                HTransformer  former = CreateWriteTransformer(stream);
                if(Null_Ptr != former)
                {
                    serialize_CUSDGW_Cmn_Out_Tag(former, &target_type);
                    DestroyTransformer(former);
                }

                DestroyOutputStream(stream);
                a_data = StreamBuffer_GetBytes(buffer);
                IOIMessageSetData(rep, a_data.pval, a_data.cnt); 
                DestroyStreamBuffer(buffer);
                array_destroy(&a_data);

                status = send_reply(session, msg, rep, status, "0");
                if(rep) IOIMessageRelease(rep);
            }
        }

    }

    return status;
}

IOIStatus recv_CUSDGW_SendAuto(IOISession session, IOIMessage msg)
{
    IOIStatus status = IOI_SUCCESS;
    CUSDGW_SendAuto_In_Tag source_type;
    CUSDGW_Cmn_Out_Tag target_type;

    IxArray ioi_data_array = IOIMessageGetDataArray(msg);
    HTransformer former = CreateByteTransformer(&ioi_data_array);
    if(Null_Ptr != former)
    {
        transform_CUSDGW_SendAuto_In_Tag(former, &source_type);
        DestroyTransformer(former);

        CUSDGW_SendAuto(&source_type, &target_type);
        if(DT_REQUEST == (IOIMessageGetDelivery(msg) & 0x000f))
        {
            IOIMessage rep = IOIMessageCreateReply(msg);
            if(Null_Ptr != rep)
            {
                IxArray a_data;
                HStreamBuffer buffer = CreateStreamByteBuffer(Null_Ptr, IX_BYTE, 5, 10, 500);
                HOutputStream stream = CreateOutputStream(buffer);
                HTransformer  former = CreateWriteTransformer(stream);
                if(Null_Ptr != former)
                {
                    serialize_CUSDGW_Cmn_Out_Tag(former, &target_type);
                    DestroyTransformer(former);
                }

                DestroyOutputStream(stream);
                a_data = StreamBuffer_GetBytes(buffer);
                IOIMessageSetData(rep, a_data.pval, a_data.cnt); 
                DestroyStreamBuffer(buffer);
                array_destroy(&a_data);

                status = send_reply(session, msg, rep, status, "0");
                if(rep) IOIMessageRelease(rep);
            }
        }

    }

    return status;
}

IOIStatus recv_CUSDGW_ViewSanpoData(IOISession session, IOIMessage msg)
{
    IOIStatus status = IOI_SUCCESS;
    CUSDGW_ViewSanpoData_In_Tag source_type;
    CUSDGW_ViewSanpoData_Out_Tag target_type;

    IxArray ioi_data_array = IOIMessageGetDataArray(msg);
    HTransformer former = CreateByteTransformer(&ioi_data_array);
    if(Null_Ptr != former)
    {
        transform_CUSDGW_ViewSanpoData_In_Tag(former, &source_type);
        DestroyTransformer(former);

        CUSDGW_ViewSanpoData(&source_type, &target_type);
        if(DT_REQUEST == (IOIMessageGetDelivery(msg) & 0x000f))
        {
            IOIMessage rep = IOIMessageCreateReply(msg);
            if(Null_Ptr != rep)
            {
                IxArray a_data;
                HStreamBuffer buffer = CreateStreamByteBuffer(Null_Ptr, IX_BYTE, 5, 10, 500);
                HOutputStream stream = CreateOutputStream(buffer);
                HTransformer  former = CreateWriteTransformer(stream);
                if(Null_Ptr != former)
                {
                    serialize_CUSDGW_ViewSanpoData_Out_Tag(former, &target_type);
                    DestroyTransformer(former);
                }

                DestroyOutputStream(stream);
                a_data = StreamBuffer_GetBytes(buffer);
                IOIMessageSetData(rep, a_data.pval, a_data.cnt); 
                DestroyStreamBuffer(buffer);
                array_destroy(&a_data);

                status = send_reply(session, msg, rep, status, "0");
                if(rep) IOIMessageRelease(rep);
            }
        }

    }

    return status;
}


